let data = [
    {
        url:"https://a.travel-assets.com/media/meso_cm/PAPI/Images/hotels/7000000/6180000/6172800/6172750/178d405d_b.jpg",
        name:"JW Marriott Hotel New Delhi Aerocity",
        location:"Aerocity",
        services:["pool","Hottub"],
        special:"Comfiest Beds, Delicious Breakfast",
        description:"Stay at unbeatable rates with complimentary breakfast and wi-fi. Free stay for kids below 12 years of age.",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{rating: "4.5/5", comment: "Wonderful",reviews:"(642 reviews)"},
        seats: " We have 5 left at",
        price:" Rs 11,250",
        total_price: "Rs 13,275 total"
    },
    {
        url:"https://a.travel-assets.com/media/meso_cm/PAPI/Images/hotels/1000000/540000/531700/531648/db6e3fdf_b.jpg",
        name:"Le Meridien New Delhi",
        location:" New Delhi",
        services:["pool"],
        special:"",
        description:"",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{rating: "4.3/5", comment: "Excellent",reviews:"(524 reviews)"},
        seats: "We have 5 left at",
        price:" Rs 8,650",
        total_price: "Rs 10,207 total"
    },
    {
        url:"https://a.travel-assets.com/media/meso_cm/PAPI/Images/hotels/4000000/3860000/3851700/3851663/958ad657_b.jpg",
        name:"The Leela Palace New Delhi",
        location:" New Delhi",
        services:["pool","Hot tub"],
        special:" The Capital's Only Modern Palace Hotel",
        description:"Discover rich diversity of cuisines, historic landmarks. International airport : 15 km, 10 mins drive from India Gate",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{rating: "4.8/5", comment: "Exceptional",reviews:"(997 reviews)"},
        seats: " ",
        price:" Rs 15,000",
        total_price: "Rs 17,700 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/1000000/470000/465100/465005/13a4747e.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"Shangri-La Eros, New Delhi",
        location:" New Delhi",
        services:["pool"],
        special:"",
        description:"",
        refund:"",
        reviews:{rating: "4.5/5", comment: "Wonderful",reviews:"(996 reviews)"},
        seats: " ",
        price:" Rs 10,800",
        total_price: "Rs 12,744 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/2000000/1310000/1304400/1304393/370d2f58.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"Taj Palace, New Delhi",
        location:" New Delhi",
        services:["pool","Hot tub"],
        special:"",
        description:"",
        refund:"Fully refundable",
        reviews:{rating: "4.5/5", comment: "Wonderful",reviews:"(1000 reviews)"},
        seats: " ",
        price:" Rs 8,075",
        total_price: "Rs 9,529 total"
    },
       {
        url:"https://images.trvl-media.com/hotels/21000000/20170000/20160800/20160759/e31ef8a9.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"The Oberoi, New Delhi",
        location:" New Delhi",
        services:["pool"],
        special:"",
        description:"",
        refund:"",
        reviews:{rating: "4.9/5", comment: "Exceptional",reviews:"(154 reviews)"},
        seats: " ",
        price:" Rs 14,175",
        total_price: "Rs 16,727 total"
    },
    {
        url:"https://a.travel-assets.com/media/meso_cm/PAPI/Images/hotels/1000000/800000/790500/790474/acc5ae1c_b.jpg",
        name:"Sheraton New Delhi Hotel",
        location:"Saket",
        services:["pool"],
        special:"",
        description:"",
        refund:"Fully refundable",
        reviews:{rating: "4.2/5", comment: "Very good",reviews:"(356 reviews)"},
        seats: "We have 5 left at",
        price:" Rs 7,200",
        total_price: "Rs 8,064 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/79000000/78700000/78692500/78692460/w1600h1230x0y2-3e9cee95.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"HOTEL ASHOKA CONTINENTAL",
        location:"Paharganj",
        services:[],
        special:"",
        description:"",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{},
        seats: "",
        price:" Rs 749",
        total_price: "Rs 749 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/1000000/80000/75800/75755/5626de23.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"The Imperial New Delhi",
        location:"Connaught Place",
        services:["pool"],
        special:"",
        description:"",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{rating: "4.7/5", comment: "Exceptional",reviews:"(457 reviews)"},
        seats: "",
        price:" Rs 16,110",
        total_price: "Rs 19,010 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/7000000/6450000/6441400/6441374/e255e840.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"The Roseate New Delhi",
        location:"New Delhi",
        services:["pool"],
        special:"",
        description:"",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{rating: "4.2/5", comment: "Very good",reviews:"(164 reviews)"},
        seats: "35% off",
        price:" Rs 11,049",
        total_price: "Rs 13,038 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/7000000/6450000/6441400/6441374/e255e840.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"The Roseate New Delhi",
        location:"New Delhi",
        services:["pool"],
        special:"",
        description:"",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{rating: "4.2/5", comment: "Very good",reviews:"(164 reviews)"},
        seats: "35% off",
        price:" Rs 11,049",
        total_price: "Rs 13,038 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/77000000/76950000/76945300/76945266/1355ab01.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"Hotel Stanley by Lord Grand",
        location:"Mahipalpur",
        services:[],
        special:"",
        description:"",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{rating: 3.5/5, comment: "Good",reviews:"(2 reviews)"},
        seats: "",
        price:" Rs 2,560",
        total_price: "Rs 2,867 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/1000000/530000/526400/526368/2239d2d7.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"Ambassador, New Delhi - IHCL SeleQtions",
        location:"New Delhi",
        services:["pool"],
        special:"",
        description:"",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{rating: "4.2/5", comment: "Very good",reviews:"(308 reviews)"},
        seats: "",
        price:" Rs 8,200",
        total_price: "Rs 9,676 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/2000000/1530000/1528800/1528788/e1cfe61e.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"Radisson Blu Plaza Delhi Airport",
        location:"Mahipalpur",
        services:["pool","Hot tub"],
        special:"",
        description:"",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{rating: "4.1/5", comment: "Very good",reviews:"(1000 reviews)"},
        seats: "",
        price:" Rs 6,399",
        total_price: "Rs 7,487 total"
    },
    {
        url:"https://images.trvl-media.com/hotels/39000000/38680000/38678300/38678265/1e0e9fc7.jpg?impolicy=resizecrop&rw=455&ra=fit",
        name:"Kelvish Hotel",
        location:"New Delhi",
        services:[],
        special:"",
        description:"",
        refund:"Fully refundable Reserve now, pay later",
        reviews:{},
        seats: "",
        price:" Rs 2,900",
        total_price: "Rs 3,248 total"
    },

];


// localStorage.setItem("delhiData",JSON.stringify(data))